version: '3.6'

services:
  api:
    container_name: mydocker-api-dev
    image: mydocker/api-dev
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 80
    env_file:
      - .env

networks:
  default:
    external:
      name: nginx-proxy
