version: '3.6'

services:
  api:
    container_name: mydocker-api
    image: mydocker/api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.production
    expose:
      - 80
    env_file:
      - .env.production

networks:
  default:
    external:
      name: nginx-proxy
