FROM node:16-alpine

ENV SRCDIR /src
RUN mkdir -p $SRCDIR/app && chown -R node:node $SRCDIR

WORKDIR $SRCDIR/app
COPY ./package.json .

RUN yarn cache clean && yarn --verbose
RUN yarn global add nodemon

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]